Makefile: fix build issue when RELEASE=1
Fix a build issue when using RELEASE=1. This was introduced
by mistake in a previous commit and this one partially reverts
the change and also addresses another issue that had not been
noticed before.

Here is the build error (RELEASE=1)
/home/gvancuts/acrn/acrn-hypervisor/build/arch/x86/cpu_primary.o /home/gvancuts/acrn/acrn-hypervisor/build/arch/x86/idt.o /home/gvancuts/acrn/acrn-hypervisor/build/arch/x86/vmx_asm.o
/home/gvancuts/acrn/acrn-hypervisor/build/boot/dmar_parse.o: In function `dmar_iterate_tbl':
/home/gvancuts/acrn/acrn-hypervisor/boot/dmar_parse.c:119: undefined reference to `get_dmar_table'
/home/gvancuts/acrn/acrn-hypervisor/build/bsp/uefi/cmdline.o: In function `handle_cmd':
/home/gvancuts/acrn/acrn-hypervisor/bsp/uefi/cmdline.c:77: undefined reference to `uart16550_set_property'
/home/gvancuts/acrn/acrn-hypervisor/bsp/uefi/cmdline.c:87: undefined reference to `uart16550_set_property'
/home/gvancuts/acrn/acrn-hypervisor/bsp/uefi/cmdline.c:89: undefined reference to `uart16550_set_property'
collect2: error: ld returned 1 exit status
make: *** [/home/gvancuts/acrn/acrn-hypervisor/build/acrn.out] Error 1

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>